### ISSUE TITLE
Erro ao Calcular Frete para Produtos acima de 999,99

### ISSUE THREAD

**Issue by meganovidades** [pedro-teixeira/correios#184]
Olá, alguém poderia me ajudar com este problema?
Para qualquer produto ou total no carrinho acima de 999,99 dá erro ao calcular o frete:

Esse método de envio está fora do ar. Por favor entre em contato conosco. ou Peso dos produtos acima do permitido pelos Correios. Por favor entre em contato conosco.

O produto em questão custa R$ 1485,00

**Comment by meganovidades** [comment]
Alguma ideia do que pode ser?

Arquivo: CorreiosMethod.php

Esta ocorrendo uma exception neste trecho

libxml_use_internal_errors(true);
            $sxe = simplexml_load_string($content);
            if (!$sxe) {
                
				throw new Exception('Bad XML [' . __LINE__ . ']');
            }


Erro Apresentado na exception:

exception 'Exception' with message 'Bad XML [343]' in public_html/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php:343 Stack trace: #0 public_html/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php(153): PedroTeixeira_Correios_Model_Carrier_CorreiosMethod->_getCorreiosReturn() #1 public_html/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php(135): PedroTeixeira_Correios_Model_Carrier_CorreiosMethod->_getQuotes() #2 public_html/app/code/core/Mage/Shipping/Model/Shipping.php(209): PedroTeixeira_Correios_Model_Carrier_CorreiosMethod->collectRates(Object(Mage_Shipping_Model_Rate_Request)) #3 public_html/app/code/core/Mage/Shipping/Model/Shipping.php(129): Mage_Shipping_Model_Shipping->collectCarrierRates('pedroteixeira_c...', Object(Mage_Shipping_Model_Rate_Request)) #4 public_html/app/code/local/Amasty/Shiprestriction/Model/Shipping/Shipping.php(9): Mage_Shipping_Model_Shipping->collectRates(Object(Mage_Shipping_Model_Rate_Request)) #5 public_html/app/code/core/Mage/Sales/Model/Quote/Address.php(944): Amasty_Shiprestriction_Model_Shipping_Shipping->collectRates(Object(Mage_Shipping_Model_Rate_Request)) #6 public_html/app/code/core/Mage/Sales/Model/Quote/Address.php(875): Mage_Sales_Model_Quote_Address->requestShippingRates() #7 public_html/app/code/core/Mage/Sales/Model/Quote/Address/Total/Shipping.php(155): Mage_Sales_Model_Quote_Address->collectShippingRates() #8 public_html/app/code/core/Mage/Sales/Model/Quote/Address.php(1013): Mage_Sales_Model_Quote_Address_Total_Shipping->collect(Object(Mage_Sales_Model_Quote_Address)) #9 public_html/app/code/core/Mage/Sales/Model/Quote.php(1331): Mage_Sales_Model_Quote_Address->collectTotals() #10 public_html/app/code/core/Mage/Checkout/Model/Cart.php(458): Mage_Sales_Model_Quote->collectTotals() #11 public_html/app/code/core/Mage/Checkout/controllers/CartController.php(144): Mage_Checkout_Model_Cart->save() #12 public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_CartController->indexAction() #13 public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index') #14 public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) #15 public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch() #16 public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array) #17 public_html/index.php(87): Mage::run('', 'store') #18 {main}

**Comment by meganovidades** [comment]
atualizado versão e problema resolvido
