### ISSUE TITLE
Erro após instalação

### ISSUE THREAD

**Issue by lmarquine** [pedro-teixeira/correios#296]
Galera, alguém sabe o que pode ser? Eu "clonei" uma loja para haver um modo de teste e ao instalar o módulo, sem nenhum outro instalado antes estou tendo o erro...

a:5:{i:0;s:346:"Error in file: "/var/www/vhosts/tinababy.com.br/httpdocs/homolog/app/code/community/PedroTeixeira/Correios/sql/pedroteixeira_correios_setup/install-4.9.0.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '212' for key 'PRIMARY', query was: INSERT INTO `catalog_eav_attribute` (`attribute_id`, `is_global`) VALUES (?, ?)";i:1;s:1140:"#0 /var/www/vhosts/tinababy.com.br/httpdocs/homolog/app/code/core/Mage/Core/Model/Resource/Setup.php(644): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /var/www/vhosts/tinababy.com.br/httpdocs/homolog/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '4.9.0')
#2 /var/www/vhosts/tinababy.com.br/httpdocs/homolog/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('4.9.0')
#3 /var/www/vhosts/tinababy.com.br/httpdocs/homolog/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /var/www/vhosts/tinababy.com.br/httpdocs/homolog/app/code/core/Mage/Core/Model/App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /var/www/vhosts/tinababy.com.br/httpdocs/homolog/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->_initModules()
#6 /var/www/vhosts/tinababy.com.br/httpdocs/homolog/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /var/www/vhosts/tinababy.com.br/httpdocs/homolog/index.php(83): Mage::run('', 'store')
#8 {main}";s:3:"url";s:9:"/homolog/";s:11:"script_name";s:18:"/homolog/index.php";s:4:"skin";s:7:"default";}

**Comment by rafaelpatro** [comment]
Não tenho certeza, mas parece que já tem algum dos atributos do módulo. É possível que tenha executado a instalação mais de uma vez, causando esse erro.

**Comment by lmarquine** [comment]
Boa noite @rafaelpatro na verdade imagino o que possa ter sido, eu migrei a loja e os atributos, desculpe incomodar, mas onde posso encontrar esses atributos para exclui-los e continuar a instalação?

**Comment by rafaelpatro** [comment]
'''xml
<product_attributes>
                        <volume_altura/>
                        <volume_comprimento/>
                        <volume_largura/>
                        <postmethods/>
                        <fit_size/>
                        <posting_days/>
                    </product_attributes>
'''
