### ISSUE TITLE
Problemas no SRO após senha obtida

### ISSUE THREAD

**Issue by mvsucupira** [pedro-teixeira/correios#297]
Pessoal, boa tarde.

Estou com a versão 4.9.0 e após uma epopeia com os Correios, finalmente conseguimos a senha para o SRO. No entanto, há algum problema que não está atualizando os status. Verifiquei o log e há uma exceção 

[19-Jul-2017 20:30:10 UTC] PHP Warning:  include(Correios/Rastro/BuscaEventos.php): failed to open stream: No such file or directory in /var/www/meuamorzinho.com.br/www/lib/Varien/Autoload.php on line 94
[19-Jul-2017 20:30:10 UTC] PHP Warning:  include(): Failed opening 'Correios/Rastro/BuscaEventos.php' for inclusion (include_path='/var/www/meuamorzinho.com.br/www/app/code/local:/var/www/meuamorzinho.com.br/www/app/code/community:/var/www/meuamorzinho.com.br/www/app/code/core:/var/www/meuamorzinho.com.br/www/lib:.:/usr/share/php') in /var/www/meuamorzinho.com.br/www/lib/Varien/Autoload.php on line 94
[19-Jul-2017 20:30:10 UTC] PHP Fatal error:  Uncaught Error: Class 'Correios_Rastro_BuscaEventos' not found in /var/www/meuamorzinho.com.br/www/.modman/correios/app/code/community/PedroTeixeira/Correios/Model/Sro.php:78

Lembro de ter visto este problema em algum outro post, mas não consegui voltar nele.

Alguém tem a solução?
Abs

**Comment by rafaelpatro** [comment]
Provavelmente vc baixou uma das versões do módulo, que estava com o caminho incorreto, para a pasta lib. Copie os arquivos de /www/app/lib/Correios para /www/lib/Correios
E recompile.

**Comment by mvsucupira** [comment]
@rafaelpatro, evoluiu, mas ainda não resolveu. Agora ele reclamou de outra classe Correios_Rastro;

[20-Jul-2017 03:38:02 UTC] PHP Warning:  include(Correios/Rastro.php): failed to open stream: No such file or directory in /var/www/meuamorzinho.com.br/www/lib/Varien/Autoload.php on line 94
[20-Jul-2017 03:38:02 UTC] PHP Warning:  include(): Failed opening 'Correios/Rastro.php' for inclusion (include_path='/var/www/meuamorzinho.com.br/www/app/code/local:/var/www/meuamorzinho.com.br/www/app/code/community:/var/www/meuamorzinho.com.br/www/app/code/core:/var/www/meuamorzinho.com.br/www/lib:.:/usr/share/php') in /var/www/meuamorzinho.com.br/www/lib/Varien/Autoload.php on line 94
[20-Jul-2017 03:38:02 UTC] PHP Fatal error:  Uncaught Error: Class 'Correios_Rastro' not found in /var/www/meuamorzinho.com.br/www/.modman/correios/app/code/community/PedroTeixeira/Correios/Model/Sro.php:89
Stack trace:
#0 /var/www/meuamorzinho.com.br/www/.modman/correios/app/code/community/PedroTeixeira/Correios/Model/Observer.php(33): PedroTeixeira_Correios_Model_Sro->request()
#1 /var/www/meuamorzinho.com.br/www/.modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Model/Schedule.php(213): PedroTeixeira_Correios_Model_Observer->sroTrackingJob(Object(Aoe_Scheduler_Model_Schedule))
#2 /var/www/meuamorzinho.com.br/www/.modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Model/Schedule.php(604): Aoe_Scheduler_Model_Schedule->runNow(true)
#3 /var/www/meuamorzinho.com.br/www/.modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#4 /var/www/meuamorzinho.com.br/www/app/code/core/Mage/Core/Model/App.php(1358): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#5 /var/www/m in /var/www/meuamorzinho.com.br/www/.modman/correios/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 89

**Comment by rafaelpatro** [comment]
Provavelmente vc não copiou todos os arquivos.
O arquivo está disponível no repositório aqui.
https://github.com/pedro-teixeira/correios/blob/master/lib/Correios/Rastro.php

**Comment by mvsucupira** [comment]
@rafaelpatro problema resolvido.
Refiz o arquivo modman e funcionou.
Obrigado.
