### ISSUE TITLE
Upgrade do modulo @rafaelpatro

### ISSUE THREAD

**Issue by phdiegues** [pedro-teixeira/correios#428]
Bom dia pessoal, tudo bem?

Primeiramente gostaria de parabenizar e deixar o meu MUITO obrigado a todos que contribuem para este módulo incrível e disponibilizado de forma gratuita na comunidade.

Há vários dias venho tentando disponibilizar a funcionalidade de geração de PLO em 2 sites que tenho, porém sem sucesso. Não aparece a opção para isso nas Ações da entrega. lembrando que já conectei o serviço com o sigep e atualizei os serviços: _"Postmethods updated successfully!"_

Pessoal, juro que tentei de tudo ao meu alcance antes de recorrer a voces aqui, sei que o tempo de todo mundo é corrido, mas agradeceria demais por qualquer ajuda.

Muito obrigado.

**Comment by rafaelpatro** [comment]
Bom dia @phdiegues 
A integração com o SIGEP ainda não foi mesclada ao repositório principal.
Vc precisa instalar o patch da PR #374

**Comment by phdiegues** [comment]
Boa tarde @rafaelpatro muito obrigado pela rápida resposta. Consegui atualizar aqui certinho porem não estou conseguindo gerar PLP, veja o log

2019-07-03T11:57:59-03:00 ERR (3): 
SoapFault exception: [soap:Server] NÃ£o foi possÃ­vel obter as etiquetas solicitadas. in /home/bigartes/public_html/lib/Correios/Sigep/AtendeClienteService.php:405
Stack trace:
#0 /home/bigartes/public_html/lib/Correios/Sigep/AtendeClienteService.php(405): SoapClient->__soapCall('solicitaEtiquet...', Array)
#1 /home/bigartes/public_html/app/code/community/PedroTeixeira/Correios/Model/Sigepweb.php(120): Correios_Sigep_AtendeClienteService->solicitaEtiquetas(Object(Correios_Sigep_SolicitaEtiquetas))
#2 /home/bigartes/public_html/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php(1202): PedroTeixeira_Correios_Model_Sigepweb->requestLabel()
#3 /home/bigartes/public_html/app/code/core/Mage/Shipping/Model/Shipping.php(504): PedroTeixeira_Correios_Model_Carrier_CorreiosMethod->requestToShipment(Object(Mage_Shipping_Model_Shipment_Request))
#4 /home/bigartes/public_html/app/code/core/Mage/Adminhtml/controllers/Sales/Order/ShipmentController.php(510): Mage_Shipping_Model_Shipping->requestToShipment(Object(Mage_Sales_Model_Order_Shipment))
#5 

Obrigado mais uma vez.

**Comment by rafaelpatro** [comment]
Consegue verificar os parâmetros dentro desse Array?

```log
#0 /home/bigartes/public_html/lib/Correios/Sigep/AtendeClienteService.php(405): SoapClient->__soapCall('solicitaEtiquet...', Array)

**Comment by rafaelpatro** [comment]
Vc cadastrou o pacote na tela de Entrega do pedido, no Magento?

**Comment by phdiegues** [comment]
Ao tentar cadastrar o pacote recebo um erro, veja no print:
![image](https://user-images.githubusercontent.com/6341299/60665961-3ec78400-9e3c-11e9-8dd7-0b739288b232.png)

**Comment by phdiegues** [comment]
Ao tentar criar o pacote, recebo o seguinte erro:

![print](https://user-images.githubusercontent.com/6341299/60666045-77675d80-9e3c-11e9-85d6-bf9e315ecf6f.jpg)

**Comment by phdiegues** [comment]
Ao tentar criar o pacote, recebo o seguinte erro:

![print](https://user-images.githubusercontent.com/6341299/60666099-9a920d00-9e3c-11e9-9d10-e4edc5682316.jpg)

**Comment by rafaelpatro** [comment]
Bom dia @phdiegues 

1. Ativa o log nas configurações do Magento, em _System > Configuration > Advanced > Developer > Log_.
1. Tenta registrar novamente o pacote.
1. Os detalhes do erro devem aparecer nos logs, em _var/system.log_ e _var/exception.log_.

**Comment by rafaelpatro** [comment]
Ops, foi mal. Seus logs já estão ativos.

Mas verifica pf qual erro aparece ao registrar o pacote.

**Comment by phdiegues** [comment]
Oi Rafael! Vamos lá... (muitíssimo obrigado pela força que está dando)

2019-07-04T10:28:59-03:00 ERR (3): 
SoapFault exception: [soap:Server] NÃ£o foi possÃ­vel obter as etiquetas solicitadas. in /home/bigartes/public_html/lib/Correios/Sigep/AtendeClienteService.php:405
Stack trace:
#0 /home/bigartes/public_html/lib/Correios/Sigep/AtendeClienteService.php(405): SoapClient->__soapCall('solicitaEtiquet...', Array)
#1 /home/bigartes/public_html/app/code/community/PedroTeixeira/Correios/Model/Sigepweb.php(120): Correios_Sigep_AtendeClienteService->solicitaEtiquetas(Object(Correios_Sigep_SolicitaEtiquetas))
#2 /home/bigartes/public_html/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php(1202): PedroTeixeira_Correios_Model_Sigepweb->requestLabel()
#3 /home/bigartes/public_html/app/code/core/Mage/Shipping/Model/Shipping.php(504): PedroTeixeira_Correios_Model_Carrier_CorreiosMethod->requestToShipment(Object(Mage_Shipping_Model_Shipment_Request))
#4 /home/bigartes/public_html/app/code/core/Mage/Adminhtml/controllers/Sales/Order/ShipmentController.php(510): Mage_Shipping_Model_Shipping->requestToShipment(Object(Mage_Sales_Model_Order_Shipment))
#5 /home/bigartes/public_html/app/code/core/Mage/Adminhtml/controllers/Sales/Order/ShipmentController.php(551): Mage_Adminhtml_Sales_Order_ShipmentController->_createShippingLabel(Object(Mage_Sales_Model_Order_Shipment))
#6 /home/bigartes/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_Order_ShipmentController->createLabelAction()
#7 /home/bigartes/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('createLabel')
#8 /home/bigartes/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /home/bigartes/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#10 /home/bigartes/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#11 /home/bigartes/public_html/index.php(88): Mage::run('', 'store')
#12 {main}

**Comment by rafaelpatro** [comment]
Puts, não tem jeito. Temos q verificar o Array.

Abre lá o arquivo na linha 120: /home/bigartes/public_html/app/code/community/PedroTeixeira/Correios/Model/Sigepweb.php

Antes da linha 120, vc coloca isso:
```php
Mage::log(print_r($params, true));
```

Testa novamente a criação do pacote, e mostra o log aqui (não esquece de ocultar dados sensíveis, como usuário/senha)

**Comment by phdiegues** [comment]
Fiz aqui, porem o log não mudou.

**Comment by phdiegues** [comment]
essa linha "Mage::log(print_r($params, true));", inclusive já estava lá.

**Comment by rafaelpatro** [comment]
Percebi que vc mandou o _exception.log_ antes.
Vc está olhando o _system.log_ tb?
